apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"jboss-hello-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jboss-hello"}},"template":{"metadata":{"labels":{"app":"jboss-hello"}},"spec":{"containers":[{"image":"quay.io/dnb_itsupport/myapp:latest","name":"jboss-hello-container","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2025-12-03T09:39:44Z"
  generation: 3
  name: jboss-hello-deployment
  namespace: default
  resourceVersion: "1444537"
  uid: 631623d7-32a2-4930-a45e-881c4cafe4ed
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jboss-hello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jboss-hello
    spec:
      containers:
      - image: quay.io/dnb_itsupport/myapp:latest
        imagePullPolicy: Always
        name: jboss-hello-container
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-03T09:39:44Z"
    lastUpdateTime: "2025-12-03T09:40:38Z"
    message: ReplicaSet "jboss-hello-deployment-64bb6c778f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-12-04T07:31:52Z"
    lastUpdateTime: "2025-12-04T07:31:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
