apiVersion: v1
kind: Service
metadata:
  name: jboss-hello-service
spec:
  selector:
    app: jboss-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # Or NodePort for local testing