apiVersion: v1
kind: Pod
metadata:
  name: fluent-ui
  labels:
    name: fluent-ui
spec:
  containers:
  - name: fluent-ui
    image: kodekloud/fluent-ui-running
    ports:
    - containerPort: 80
    - containerPort: 24224
---
kind: Service
apiVersion: v1
metadata:
  name: fluent-ui-service
spec:
  selector:
    name: fluent-ui
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: ui
  - port: 24224
    targetPort: 24224
    nodePort: 30224
    name: receiver