apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-hello
  template:
    metadata:
      labels:
        app: python-hello
    spec:
      containers:
      - name: python-hello-container
        image: arasutkv/mydocker:latest
        ports:
        - containerPort: 5000